apiVersion: v1
kind: Pod
metadata:
  name: test-1
spec:
  restartPolicy: OnFailure
  containers:
  - name: gpu-test
    image: nvcr.io/nvidia/pytorch:23.07-py3
    command: [ "nvidia-smi" ]
    args: ["-L" ]
    resources:
      limits:
          nvidia.com/mig-1g.10gb: 1
  nodeSelector:
      nvidia.com/gpu.product : NVIDIA-H100-PCIe

---

apiVersion: v1
kind: Pod
metadata:
  name: test-2
spec:
  restartPolicy: OnFailure
  containers:
  - name: gpu-test
    image: nvcr.io/nvidia/pytorch:23.07-py3
    command: [ "nvidia-smi" ]
    args: ["-L" ]
    resources:
      limits:
          nvidia.com/mig-1g.10gb: 1
  nodeSelector:
      nvidia.com/gpu.product : NVIDIA-H100-PCIe

---

apiVersion: v1
kind: Pod
metadata:
  name: test-3
spec:
  restartPolicy: OnFailure
  containers:
  - name: gpu-test
    image: nvcr.io/nvidia/pytorch:23.07-py3
    command: [ "nvidia-smi" ]
    args: ["-L" ]
    resources:
      limits:
          nvidia.com/mig-1g.10gb: 1
  nodeSelector:
      nvidia.com/gpu.product : NVIDIA-H100-PCIe