apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: nvidia-gpu-operator
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2024-05-21T13:25:08Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: nvidia-gpu-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/version: v0.14.2
    helm.sh/chart: node-feature-discovery-0.14.2
    role: gc
  name: nvidia-gpu-operator-node-feature-discovery-gc
  namespace: kube-system
  resourceVersion: "17528592495"
  uid: 7163e0b0-5096-4e24-a6dd-172335eb098b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: nvidia-gpu-operator
      app.kubernetes.io/name: node-feature-discovery
      role: gc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nvidia-gpu-operator
        app.kubernetes.io/name: node-feature-discovery
        role: gc
    spec:
      containers:
      - args:
        - -gc-interval=1h
        command:
        - nfd-gc
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: registry.k8s.io/nfd/node-feature-discovery:v0.14.2
        imagePullPolicy: IfNotPresent
        name: gc
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: node-feature-discovery
      serviceAccountName: node-feature-discovery
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-21T13:25:15Z"
    lastUpdateTime: "2024-05-21T13:25:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-21T13:25:08Z"
    lastUpdateTime: "2024-05-21T13:25:15Z"
    message: ReplicaSet "nvidia-gpu-operator-node-feature-discovery-gc-54c944c8d7"
      has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
