apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: nvidia-gpu-operator
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2024-05-21T13:25:08Z"
  generation: 1
  labels:
    app.kubernetes.io/component: gpu-operator
    app.kubernetes.io/instance: nvidia-gpu-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gpu-operator
    app.kubernetes.io/version: v23.9.2
    helm.sh/chart: gpu-operator-v23.9.2
    nvidia.com/gpu-driver-upgrade-drain.skip: "true"
  name: gpu-operator
  namespace: kube-system
  resourceVersion: "17676295453"
  uid: 4bbb5984-65fe-4244-89f3-822b3fa7bed2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gpu-operator
      app.kubernetes.io/component: gpu-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/scc: restricted-readonly
      creationTimestamp: null
      labels:
        app: gpu-operator
        app.kubernetes.io/component: gpu-operator
        app.kubernetes.io/instance: nvidia-gpu-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: gpu-operator
        app.kubernetes.io/version: v23.9.2
        helm.sh/chart: gpu-operator-v23.9.2
        nvidia.com/gpu-driver-upgrade-drain.skip: "true"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - ""
            weight: 1
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: In
                values:
                - ""
            weight: 1
      containers:
      - args:
        - --leader-elect
        - --zap-time-encoding=epoch
        - --zap-log-level=info
        command:
        - gpu-operator
        env:
        - name: WATCH_NAMESPACE
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DRIVER_MANAGER_IMAGE
          value: nvcr.io/nvidia/cloud-native/k8s-driver-manager:v0.6.5
        image: nvcr.io/nvidia/gpu-operator:v23.9.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: gpu-operator
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 350Mi
          requests:
            cpu: 200m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host-etc/os-release
          name: host-os-release
          readOnly: true
      dnsPolicy: ClusterFirst
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: gpu-operator
      serviceAccountName: gpu-operator
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Equal
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Equal
      volumes:
      - hostPath:
          path: /etc/os-release
          type: ""
        name: host-os-release
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-21T13:25:08Z"
    lastUpdateTime: "2024-05-21T13:25:39Z"
    message: ReplicaSet "gpu-operator-5984d665bf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-05-28T00:02:19Z"
    lastUpdateTime: "2024-05-28T00:02:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
