apiVersion: v1
kind: Pod
metadata:
  name: pytorch-gpu-pod-mig-super
spec:
  containers:
  - name: pytorch-gpu-container-mig-super
    image: pytorch/pytorch:latest
    resources:
      limits:
        nvidia.com/mig-1g.10gb: 1
    command: ["python", "-c"]
    args:
      - |
        import torch
        import time
        a = torch.randn(50000, 50000).cuda()
        b = torch.randn(50000, 50000).cuda()
        while True:
          c = torch.matmul(a, b)
          time.sleep(1)
  restartPolicy: Never
  nodeSelector:
      nvidia.com/gpu.product : NVIDIA-H100-PCIe