apiVersion: v1
kind: Pod
metadata:
  name: pytorch-gpu-pod
spec:
  containers:
  - name: pytorch-gpu-container
    image: pytorch/pytorch:latest
    resources:
      limits:
        nvidia.com/gpu: 1 #
    command: ["python", "-c"]
    args:
      - |
        import torch
        import time
        a = torch.randn(1000, 1000).cuda()
        b = torch.randn(1000, 1000).cuda()
        while True:
          c = torch.matmul(a, b)
          time.sleep(1)
  restartPolicy: Never