apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: sleepy
          image: busybox:latest
          command: ["sleep", "120"]
          resources:
            limits:
              nvidia.com/mig-1g.10gb: 1